// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_or_create_client`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StoreConfig`

/// Must be called once at startup, before any other bridge call that needs the client.
/// The store holds E2EE keys, so it's encrypted with `passphrase`.
Future<void> setStore({required String path, required String passphrase}) =>
    RustLib.instance.api.crateApiClientSetStore(
      path: path,
      passphrase: passphrase,
    );
