// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_room`

/// Latest `limit` text messages of a room, oldest first.
Future<List<MessageSummary>> getMessages({
  required String homeserverUrl,
  required String roomId,
  required int limit,
}) => RustLib.instance.api.crateApiMessagesGetMessages(
  homeserverUrl: homeserverUrl,
  roomId: roomId,
  limit: limit,
);

/// Sends a plain-text message, returns its event ID.
Future<String> sendTextMessage({
  required String homeserverUrl,
  required String roomId,
  required String body,
}) => RustLib.instance.api.crateApiMessagesSendTextMessage(
  homeserverUrl: homeserverUrl,
  roomId: roomId,
  body: body,
);

class MessageSummary {
  final String eventId;
  final String sender;
  final String body;
  final PlatformInt64 timestampMs;
  final bool isOwn;

  const MessageSummary({
    required this.eventId,
    required this.sender,
    required this.body,
    required this.timestampMs,
    required this.isOwn,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      sender.hashCode ^
      body.hashCode ^
      timestampMs.hashCode ^
      isOwn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageSummary &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          sender == other.sender &&
          body == other.body &&
          timestampMs == other.timestampMs &&
          isOwn == other.isOwn;
}
