// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `reencode_avatar`

Future<ProfileInfo> getProfile({required String homeserverUrl}) => RustLib
    .instance
    .api
    .crateApiProfileGetProfile(homeserverUrl: homeserverUrl);

/// An empty (or whitespace-only) name clears the display name.
Future<void> setDisplayName({
  required String homeserverUrl,
  required String name,
}) => RustLib.instance.api.crateApiProfileSetDisplayName(
  homeserverUrl: homeserverUrl,
  name: name,
);

/// Re-encodes the image and makes it the account avatar.
/// Avatars are public and unencrypted, so the original file never leaves the device.
Future<void> setAvatar({
  required String homeserverUrl,
  required List<int> data,
}) => RustLib.instance.api.crateApiProfileSetAvatar(
  homeserverUrl: homeserverUrl,
  data: data,
);

Future<void> removeAvatar({required String homeserverUrl}) => RustLib
    .instance
    .api
    .crateApiProfileRemoveAvatar(homeserverUrl: homeserverUrl);

class ProfileInfo {
  final String userId;
  final String? displayName;
  final Uint8List? avatar;

  const ProfileInfo({required this.userId, this.displayName, this.avatar});

  @override
  int get hashCode => userId.hashCode ^ displayName.hashCode ^ avatar.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileInfo &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          avatar == other.avatar;
}
