// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `room_summaries`

/// Streams the room list: once right away (from the local store), then again
/// whenever the sync loop updates any room. Stops when Dart cancels the stream.
/// Errors go into the stream (a returned Err would never reach the Dart listener).
Stream<List<RoomSummary>> watchRooms({required String homeserverUrl}) =>
    RustLib.instance.api.crateApiRoomsWatchRooms(homeserverUrl: homeserverUrl);

class RoomSummary {
  final String id;
  final String name;

  const RoomSummary({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}
