// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `run_sync_loop`

/// Starts the background sync loop, no-op if it's already running.
/// Needs an authenticated client (call after login / restore_session).
Future<void> startSync({required String homeserverUrl}) =>
    RustLib.instance.api.crateApiSyncStartSync(homeserverUrl: homeserverUrl);
